---
# roles/loadbalancer/tasks/main.yml
- name: Install python setuptools and docker
  yum:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - python-setuptools
    - docker

- name: Start docker
  service:
    name: docker
    state: started

- name: Install pypi
  easy_install: name=pip

- name: Install docker-py to latest
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
    - docker-py

- name: Pull loadbalancer image
  docker_image:
    name: tobyosul/lbnginx

- name : (Re)start loadbalaner container
  docker_container:
    name: lbnginx
    image: tobyosul/lbnginx
    state: started
    restart: yes
    ports:
    - "8080:80"

